// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgfnqxucvtjkinqyvvrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhnZm5xeHVjdnRqa2lucXl2dnJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4ODE0MzgsImV4cCI6MjA3NDQ1NzQzOH0.UmwcR97iz_srTWurA7J_0awC-IjgTSeQ6xZwg3WndJY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});